apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cnpm-food2
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jelly1810/cnpm-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: API_GATEWAY_URL
          value: "http://api-gateway:9001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cnpm-food2
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 4300
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend
